const ACTION_CONSTANTS = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
  SET_WISHLIST_NAME: "SET_WISHLIST_NAME",
  SET_THEME: "SET_THEME",
  SET_SEARCH_TEXT: "SET_SEARCH_TEXT",
  SET_IMDB_ID: "SET_IMDB_ID",
  SET_PRIMARY_COLOR: "SET_PRIMARY_COLOR",
  SET_WISHLIST: "SET_WISHLIST",

  //reset

  RESET_WISHLIST: "RESET_WISHLIST",
  RESET_THEME: "RESET_THEME",
  RESET_MOVIE: "RESET_MOVIE",
};

export default ACTION_CONSTANTS;
